name: Deploy backend

on:
  workflow_call:
    inputs:
      deployment_environment:
        description: 'Environment to deploy to - stage or prod'
        required: true
        default: 'stage'
        type: string

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set environment variables'
        run: |
          if ['${{ inputs.deployment_environment }}' == 'stage' ]; then
            echo 'Setting variables for staging ... '
            echo 'export TFSTATE_S3_KEY=global/CRC-BACKEND-STAGE/terraform.tfstate' >> $GITHUB_ENV
            echo $GITHUB_ENV
          else
            echo 'Setting variables for production ... '
            echo 'export TFSTATE_S3_KEY=global/CRC-BACKEND-PROD/terraform.tfstate' >> $GITHUB_ENV
            echo $GITHUB_ENV
          fi

      - name: 'TEST - Print the env variable'
        run: |
          echo TFSTATE_S3_KEY is set to: $TFSTATE_S3_KEY