name: Deploy backend

on:
  workflow_call:
    inputs:
      deployment_environment:
        description: 'Environment to deploy to - stage or prod'
        required: true
        default: 'stage'
        type: string

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: 'TEST - Print the input to STDOUT'
        run: |
          echo Environment is ${{ inputs.deployment_environment }}