name: Deploy backend

on:
  workflow_call:
    inputs:
      deployment_environment:
        description: 'Environment to deploy to - stage or prod'
        required: true
        default: 'stage'
        type: string

jobs:
  tf-deploy-to-aws:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Set environment variables'
        run: |
          if [[ '${{ inputs.deployment_environment }}' == 'stage' ]]; then
            echo 'Setting variables for staging ... '
            echo 'TFSTATE_S3_KEY=global/CRC-BACKEND-STAGE/terraform.tfstate' >> $GITHUB_ENV
            echo 'TF_deployment_env=stage' >> $GITHUB_ENV
          else
            echo 'Setting variables for production ... '
            echo 'TFSTATE_S3_KEY=global/CRC-BACKEND-PROD/terraform.tfstate' >> $GITHUB_ENV
            echo 'TF_deployment_env=prod' >> $GITHUB_ENV
          fi

      - name: 'TEST - Print the env variable'
        run: |
          echo TFSTATE_S3_KEY is set to: $TFSTATE_S3_KEY
          echo TF_deployment_env is: $TF_deployment_env

      - name: Install Terraform
        id: install-tf
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Print TF version
        id: print-tf-ver
        run: |
          terraform --version

      - name: Configure AWS credentials for staging account
        if: ${{ inputs.deployment_environment == 'stage' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_STAGING_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-session-name: GitHub-Staging-Workflow-Session
          role-duration-seconds: 900

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity