name: Deploy backend

on:
  workflow_call:
    inputs:
      deployment_environment:
        description: 'Environment to deploy to - stage or prod'
        required: true
        type: string
        default: 'stage'
      stage_destroy:
        description: 'Set deployment_environment to stage and set stage_destroy to true to destroy the staging environment. Will NOT destroy prod environment.'
        required: false
        type: boolean
        default: false


jobs:
  tf-deploy-to-aws:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Set environment variables'
        run: |
          if [[ '${{ inputs.deployment_environment }}' == 'stage' ]]; then
            echo 'Setting variables for staging ... '
            echo 'TFSTATE_S3_KEY=global/CRC-BACKEND-STAGE/terraform.tfstate' >> $GITHUB_ENV
            echo 'TF_deployment_env=stage' >> $GITHUB_ENV
          else
            echo 'Setting variables for production ... '
            echo 'TFSTATE_S3_KEY=global/CRC-BACKEND-PROD/terraform.tfstate' >> $GITHUB_ENV
            echo 'TF_deployment_env=prod' >> $GITHUB_ENV
          fi

      - name: Install Terraform
        id: install-tf
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Print TF version
        id: print-tf-ver
        run: |
          terraform --version

      - name: Configure AWS credentials for staging account
        if: ${{ inputs.deployment_environment == 'stage' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_STAGING_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-session-name: GitHub-Staging-Workflow-Session
          role-duration-seconds: 900

      - name: Configure AWS credentials for production account
        if: ${{ inputs.deployment_environment == 'prod' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_PRODUCTION_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-session-name: GitHub-Production-Workflow-Session
          role-duration-seconds: 900

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Initialize Terraform
        id: tf-init
        working-directory: backend/terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_TERRAFORM_STATE_BUCKET }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ secrets.AWS_TERRAFORM_STATELOCK_TABLE }}" \
            -backend-config="encrypt=true" \
            -backend-config="key=$TFSTATE_S3_KEY"

      - name: Terraform plan
        id: tf-plan
        working-directory: backend/terraform
        run: |
          terraform plan -var "deployment_env=$TF_deployment_env"