name: Deploy backend

on:
  workflow_dispatch:
    inputs:
      deployment_environment:
        description: 'Environment to deploy to - stage or prod'
        required: true
        default: 'stage'
        type: choice
        options:
        - stage
        - prod

jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - name: 'TEST - Print the input to STDOUT'
        run: |
        echo Environment is ${{ inputs.deployment_environment }}