name: Backend pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/src/**'
      - 'backend/test/unittest_**.py'
      - 'backend/test/test_**.py'

jobs:
  unittest:
    name: Run unit tests
    uses: ./.github/workflows/run-unittest.yml

  deploy_backend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy API to staging
    needs: unittest
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  api_test:
    needs: deploy_backend_staging
    if: ${{ needs.deploy_backend_staging.result == 'success' }}
    name: Run tests to the deployed API
    uses: ./.github/workflows/run-api-test.yml
    with:
      api_gw_custom_domain: ${{ needs.deploy_backend_staging.outputs.TF_api_gw_custom_domain }}

  deploy_backend_production:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy API to production
    needs: api_test
    if: ${{ needs.api_test.result == 'success' }}
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: prod
      stage_destroy: false

  destroy_backend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Destroy the staging API
    needs: api_test
    if: ${{ needs.api_test.result == 'success' }}
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: true