name: Run API tests

on:
  workflow_call:
    inputs:
      api_gw_custom_domain:
        description: 'API gateway domain to run API tests on. Expects string without any http(s):// prefix'
        required: true
        type: string
        default: ''

jobs:

  api_test:
    name: Run tests to the deployed API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies for API test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-api-test.txt

      - name: Sleep for 120 seconds to wait for full API deployment with SSL
        run: sleep 120s
        shell: bash

      - name: Test if API was deployed and passing tests
        id: test-api-gw
        working-directory: backend/terraform
        run: |
          pytest -v ../test/test_api_endpoint.py \
            --api-gw-domain="${{ inputs.api_gw_custom_domain }}"