name: Run frontend pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/src/**.html'
      - 'frontend/src/**.js'

jobs:

  deploy_frontend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy frontend to staging
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  deploy_backend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy backend to staging
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  e2e_test:
    name: Run Cypress tests
    needs: [ deploy_frontend_staging, deploy_backend_staging ]
    if: ${{ needs.deploy_frontend_staging.result == 'success' && needs.deploy_backend_staging.result =='success' }}
    uses: ./.github/workflows/run-cypress.yml
    with:
      site_domain: ${{ needs.deploy_frontend_staging.outputs.TF_cf_alias_domain }}

  deploy_frontend_production:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy frontend to production
    needs: e2e_test
    if: ${{ needs.e2e_test.result == 'success' }}
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      deployment_environment: prod
      stage_destroy: false

  destroy_frontend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Destroy frontend staging
    needs: e2e_test
    if: ${{ needs.e2e_test.result == 'success' }}
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      deployment_environment: stage
      stage_destroy: true