name: Run unit test on Lambda package

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/src/**'
      - 'backend/test/unittest_**.py'

jobs:
  unittest:
    name: Perform unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies for unit test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-unittest.txt
      - name: Run tests
        id: python-test
        run: |
          pytest -v backend/test/unittest_lambda.py

  deploy_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy API to staging
    needs: unittest
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  api_test:
    needs: deploy_staging
    name: Run tests to the deployed API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies for API test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-api-test.txt

      - name: Sleep for 120 seconds to wait for full API deployment with SSL
        run: sleep 120s
        shell: bash

      - name: Test if API was deployed and passing tests
        id: test-api-gw
        working-directory: backend/terraform
        run: |
          pytest -v ../test/test_api_endpoint.py --api-gw-domain="${{ needs.deploy_staging.outputs.TF_api_gw_customain_domain }}"