name: Test the Python package

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tests
        id: python-test
        run: |
          python -m unittest discover -s test/ -p "test_*.py"

  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Install Terraform
        id: install-tf
        uses: hashicorp/setup-terraform@v2

      - name: Print TF version
        run: |
          terraform --version

      - name: Configure AWS credentials for staging account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_STAGING_ROLE_TO_ASSUME }}
          aws-region: us-east-1
          role-session-name: GitHub-Staging-Workflow-Session
          role-duration-seconds: 900

      - name: Initialize Terraform
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_TERRAFORM_STATE_BUCKET }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ secrets.AWS_TERRAFORM_STATELOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Test Terraform
        working-directory: terraform
        run: |
          terraform plan