name: Run frontend tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/src/**.html'
      - 'frontend/src/**.js'

jobs:

  deploy_frontend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy frontend to staging
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  deploy_backend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy backend to staging
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  e2e_test:
    name: Perform Cypress tests
    needs: [ deploy_frontend_staging, deploy_backend_staging ]
    uses: ./.github/workflows/run-cypress.yml
    with:
      site_domain: ${{ needs.deploy_frontend_staging.outputs.TF_cf_alias_domain }}