name: Test the Python package

on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run tests
        id: python-test
        run: |
          python -m unittest discover -s test/ -p "test_*.py"

  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Install Terraform
        id: install-tf
        uses: hashicorp/setup-terraform@v2

      - name: Print TF version
        run: |
          terraform --version