name: Run frontend tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/src/**.html'
      - 'frontend/src/**.js'

jobs:

  deploy_frontend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy frontend to staging
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  deploy_backend_staging:
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    name: Deploy backend to staging
    uses: ./.github/workflows/deploy-backend.yml
    with:
      deployment_environment: stage
      stage_destroy: false

  e2e_test:
    name: Perform Cypress tests
    needs: [ deploy_frontend_staging, deploy_backend_staging ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set frontend deploy output to GitHub env
        run: |
          echo "${{ needs.deploy_backend_staging.outputs.TF_api_gw_custom_domain }}"
          echo "CYPRESS_site_url=https://${{ needs.deploy_frontend_staging.outputs.TF_cf_alias_domain }}" >> $GITHUB_ENV

      - name: Run Cypress
        id: run_cypress
        uses: cypress-io/github-action@v5
        with:
          spec: ./frontend/cypress/e2e/**.cy.js